# Must be put in .config/ortscripts/ 

Version: 0.2b 
ObsidianMainFolder: /home/anon/ortup/important/notes/ortvault

# The specifc names for the folders inside your vault 
ObsidianResourceFolder: resources
# The name of the folder where your notes reside 
NotesFolder: notes

# This will be in your resources folder 
GameFolder: game
AnimeFolder: anime_db
MindPalaceFolder: mindpalace


# Keyboard
# select your device with evtest
KeyboardName: NuPhy
Profile1ScreenshotButton: KEY_SYSRQ
Profile1RecordButton: KEY_INSERT
Profile1AudioButton: KEY_HOME
Profile1EscapeButton: KEY_END

# Gamepad 
GamePadName: Xbox
Profile2ScreenshotButton: KEY_RECORD
Profile2RecordButton: BTN_MODE
Profile2EscapeButton: ABS_HAT0Y


# This value shaves off seconds of the total playtime recorded in a session to compensate for startup time of the game.  
StartupCompensator: 30


# Option to insert a timeline inside the note that tracks on what day you played for how many minutes, this has nothing to do with playtime recording, it's just an extra 
TimelineOption: 1
# Option to add a limit on how many minutes the first recorded session must be to be inserted into note, to avoid cluttering the timeline with pointless sessions 
SessionLimit: 10
