#! /usr/bin/env fish 

# gameinit creates this file on launch 
set obsidian_file (cat /tmp/obsidian_last.txt)

function help_function
    echo -e "Usage: gn \"message\""
    echo "Options:"
    echo "  -m       Generic message"
    echo "  -t       Create genereic #task"
    echo "  -r       Create something to #research"
    echo "  -l       Create #highlight"
    echo "  -q       Create quote"
    echo "  -s       Add newline after quote"
    echo "  -d       Create message to delete"
end

argparse --name=gn h/help t/task d/delete r/research q/question s/space l/link 'n/name=' -- $argv
or return

if set -q _flag_h
    help_function
    exit
end

if set -q _flag_t
    echo -e "- [ ] #task $argv[1]\n" >>$obsidian_file
    exit
end

if set -q _flag_d
    echo -e "- [f] #delete $argv[1]\n" >>$obsidian_file
    exit
end

if set -q _flag_r
    echo -e "- [ ] #research $argv[1]\n" >>$obsidian_file
    exit
end

if set -q _flag_l
    echo -e "[$argv[1]]($argv[2])\n" >>$obsidian_file
    exit
end

if set -q _flag_q
    set raw_quote
    set highlight
    echo -n | xclip -selection clipboard
    echo "Insert Quote"
    while true
        set clipboard (xclip -o -selection clipboard)
        if not test -z $clipboard
            set raw_quote (echo $clipboard)
            echo -n | xclip -selection clipboard
            echo "Insert Highlight"
            while test -z $highlight
                set highlight (xclip -o -selection clipboard)
                sleep 1
            end
            set format_quote (echo $raw_quote | sed "s/$highlight/==$highlight==/g")
            echo "" >>$obsidian_file
            echo ">[!quote] $format_quote" >>$obsidian_file
            echo -n | xclip -selection clipboard
            set -e highlight
            echo "Insert Quote"

            if set -q _flag_s
                echo "" >>$obsidian_file
            end
        end
        sleep 1
    end
end

echo "" >>$obsidian_file
echo "$argv[1]" >>$obsidian_file
