#! /usr/bin/env fish 
set script_dir (realpath (status dirname))
set obsidian (ot_config_grab "ObsidianMainFolder")
set main_res_folder (ot_config_grab "ObsidianResourceFolder")
set main_note_folder (ot_config_grab "NotesFolder")
set folder_note $obsidian/$main_note_folder/highlights
mkdir -p $folder_note
set folder_res (ot_config_grab "CharacterRes")

argparse --name=gn h/help 'n/name=' -- $argv
or return

function base_tag_insert
    if rg "  - highlight" $obsidian_md
    else
        sed -i '/^tags:/a\  - highlight' $obsidian_md
    end

    if not grep -q "Info Base.base" $obsidian_md
        #sed -i "/^tags:/i\\cssclasses:" "$obsidian_md"
        # sed -i "/^cssclasses:/a\\  - table-max" "$obsidian_md"
        if string match manga $medium
            set input_file "![[Manga Info Base.base]]"
        else if string match vn $medium
            set input_file "![[VN Info Base.base]]"
        else if string match anime $medium
            set input_file "![[Anime Info Base.base]]"
        else
            set input_file "![[Game Info Base.base]]"
        end

        if cat $obsidian_md | grep "# Info"
            sed -i "/# Info/a\\$input_file" $obsidian_md
        else
            sed -i "$(awk '/---/{c++} c==2{print NR; exit}' "$obsidian_md")a\\
$input_file
" "$obsidian_md"
        end
    end
end

set obsidian_md (fd -t f -F ".md" $obsidian | sort -r | fzf --delimiter='/' --with-nth=-1 --style=full --preview "$script_dir/scripts/media-fzf.fish {}")
set obs_name (basename -s ".md" $obsidian_md)
set hyphen_title_series (echo $obs_name | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')

if cat $obsidian_md | rg "platform: doujin"
    set medium doujin
else if cat $obsidian_md | rg "  - vn"
    set medium vn
else if cat $obsidian_md | rg "  - weg"
    set medium weg
else if cat $obsidian_md | rg "  - game"
    set medium game
else if cat $obsidian_md | rg "  - anime"
    set medium anime
else if cat $obsidian_md | rg "  - manga"
    set medium manga
else if cat $obsidian_md | rg "  - ln"
    set medium ln
else if cat $obsidian_md | rg "type: movie"
    set medium film
else if cat $obsidian_md | rg "type: tv"
    set medium tv
end

echo "Name of the Highlight:"
read name
echo "Value of the Highlight:"
read value

set md "$folder_note/$name - $obs_name.md"
set creation_date (date +"%Y-%m-%dT%H:%M:%S")

base_tag_insert

if rg "series:" $obsidian_md
    set series (rg -zPU 'series:[\s\S]*?(?=\n[a-zA-Z])' $obsidian_md)
end

echo --- >>$md
echo "name: \"$name\"" >>$md

if not test -z $series
    for i in $series
        echo $i >>$md
    end
end

echo "origin: \"[[$obs_name]]\"" >>$md
echo "creation_date: $creation_date" >>$md
echo "tags:" >>$md
echo "value: $value" >>$md
echo "medium: \"$medium\"" >>$md
echo "highlight: \"$highlight\"" >>$md
echo "details: \"$details\"" >>$md
echo "sequence: " >>$md
echo "counter: " >>$md
echo "last_seen: " >>$md
echo "category: Highlight" >>$md
echo --- >>$md
