#! /usr/bin/env fish 
set script_dir (realpath (status dirname))
set obsidian (ot_config_grab "ObsidianMainFolder")
set main_res_folder (ot_config_grab "ObsidianResourceFolder")
set main_note_folder (ot_config_grab "NotesFolder")
set folder_note $obsidian/$main_note_folder/info
mkdir -p $folder_note

argparse --name=gn h/help 'n/name=' -- $argv
or return

function base_tag_insert
    if not grep -q "Info Base.base" $obsidian_md
        if cat $obsidian_md | grep "# Info"
            sed -i "/# Info/a\\$input_file" $obsidian_md
        else
            sed -i "$(awk '/---/{c++} c==2{print NR; exit}' "$obsidian_md")a\\
$input_file
" "$obsidian_md"
        end
    end
end

set obsidian_md (fd -t f -F ".md" $obsidian | sort -r | fzf --delimiter='/' --with-nth=-1 --style=full --preview "$script_dir/scripts/media-fzf.fish {}")
set obs_name (basename -s ".md" $obsidian_md)
set hyphen_title_series (echo $obs_name | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')

echo "Title of the Info:"
read title

set info_type (gum choose --limit 1 "Story" "Lore" "Trivia" "Character" "Gameplay" "Outsource")

if string match Outsource $info_type
    set priority 1
else if string match Character $info_type
    set priority 3
else if string match Trivia $info_type
    set priority 4
else
    set priority 2
end

set folder_obs $folder_note/$obs_name
mkdir -p $folder_obs
set md "$folder_obs/$title - $obs_name.md"
set creation_date (date +"%Y-%m-%dT%H:%M:%S")

base_tag_insert

if rg "series:" $obsidian_md
    set series (rg -zPU 'series:[\s\S]*?(?=\n[a-zA-Z])' $obsidian_md)
end

echo --- >>$md
echo "name: \"$title\"" >>$md
echo "origin: \"[[$obs_name]]\"" >>$md
echo "creation_date: $creation_date" >>$md
echo "tags:" >>$md
echo "info: \"$info_type\"" >>$md
echo "sequence: " >>$md
echo "priority: $priority" >>$md
echo "category: Info" >>$md
echo --- >>$md
