#! /usr/bin/env fish 
# yt-mp -g "Ancient Lake" "Diddy Kong Racing"

argparse --name=gn h/help g/game l/location 'n/name=' -- $argv
or return

set main_folder (ot_config_grab "ObsidianMainFolder")
set resources_folder (ot_config_grab "ObsidianResourceFolder")
set obsidian $main_folder/(ot_config_grab "NotesFolder")/
set obsidian_md (find $obsidian -type f -name "$argv[1].md")
set title "$argv[1]"
set folder_title (echo $title | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
set mindpalace_name (ot_config_grab "MindPalaceFolder")
set screenshot_folder "$resources_folder/$mindpalace_name/youtube/$folder_title"

set screenshot_folder "$resources_folder/$mindpalace_name/youtube/game/$folder_title"
set obsidian_md "$obsidian/locations/game/$argv[1].md"

if test -d $screenshot_folder
    echo "folder exists"
else
    mkdir $screenshot_folder
end
