#! /usr/bin/env fish

function help_function
    echo "By default selection from all pool files."

    echo "Options:"
    echo "  -h       help"
    echo "  -t       Filter selection based on a tag"
    echo "  -d       Filter selection based on two tags"
    echo "  -i       History, selection decending from the most recent file"
    echo "  -r       Random selection. Works with -t and -d"
    echo "  -u       Select unrated files. Works with -t, -d and/or -r"
    echo "  -b       100 Value (bookmarked)"
    echo "  -o       Filter selection based on origin"
    echo "  -p       Filter selection based on parent"
end

argparse --name=pool t/tag d/double i/history r/random u/unrated b/bookmark o/origin p/parent h/help 'n/name=' -- $argv
or return

set script_dir (realpath (status dirname))
set obsidian_folder (ot_config_grab "ObsidianMainFolder")
set notes (ot_config_grab "NotesFolder")
set default_pool_array (rg -l "^  - pool\$" $obsidian_folder/$notes)
set multi_flag_check 1

if set -q _flag_h
    help_function
    exit
end

if set -q _flag_t
    set chosen_tag (awk '/^tags:/ {flag=1; next} flag && /^  - / {print $2} flag && !/^  - / {flag=0}' $default_pool_array | sort -u | fzf)
    set multi_flag_check 0
end

if set -q _flag_d
    set chosen_tag (awk '/^tags:/ {flag=1; next} flag && /^  - / {print $2} flag && !/^  - / {flag=0}' $default_pool_array | sort -u | fzf)
    set filtered_pool (rg -l "^  - $chosen_tag\$" $default_pool_array)
    set chosen_tag (rg -o --no-filename "^  - [a-z]*" $filtered_pool | sed 's/[ -]//g' | sort -u | fzf)
    set multi_flag_check 0
end

if set -q _flag_o
    set chosen_tag (rg -oP --no-filename "(?<=origin: ).*" $default_pool_array | sort -u | fzf)
    set target_md (rg -l "origin: $chosen_tag" $default_pool_array | fzf)
end

if set -q _flag_p
    set chosen_tag (rg -oP --no-filename "(?<=parent: \"\[\[)[^\]]*" $default_pool_array | sort -u | fzf)
    set target_md (rg -l "parent: \"\[\[$chosen_tag" $default_pool_array | fzf --delimiter='/' --with-nth=-1)
end

if set -q _flag_i
    set target_md (gum choose (cat $HOME/.config/ortscripts/pool-history))
end

if set -q _flag_r
    if set -q _flag_t
        set multi_flag_check 1
        set default_pool_array (rg -l "\- $chosen_tag" $default_pool_array)
    end
    set array_length (count $default_pool_array)
    set random_selection (random 1 $array_length)
    set target_md $default_pool_array[$random_selection]
end

if set -q _flag_u
    if set -q _flag_t
        set multi_flag_check 1
        set default_pool_array (rg -l "\- $chosen_tag" $default_pool_array)
    end

    if set -q _flag_r
        set default_pool_array (grep -L "session:" $default_pool_array)
        set array_length (count $default_pool_array)
        set random_selection (random 1 $array_length)
        set target_md $default_pool_array[$random_selection]
    else
        set target_md (grep -L "session:" $default_pool_array | fzf)
    end
end

if set -q _flag_b
    set target_md (grep -l "value: 100" $default_pool_array | fzf)
end

if test $multi_flag_check -eq 0
    set target_md (rg -l "\- $chosen_tag" $default_pool_array | fzf)
end

if test -z "$target_md"
    set target_md (rg -l "\- pool" $obsidian_folder/$notes | fzf --delimiter='/' --with-nth=-1)
end

set base_name (basename $target_md)
set history_config "$HOME/.config/ortscripts/pool-history"
sed -i "/$base_name/d" $history_config
sed -i "1i $target_md" $history_config

echo $target_md >/tmp/the-pool.txt

if grep -q 'uuid:' $target_md
    set uuid (grep -oP '(?<=uuid: ).*' $target_md)
else
    set uuid (uuidgen)
    sed -i "/^tags:/i\\uuid: $uuid" "$target_md"
end

if grep -qoP "(?<=session: ).*" $target_md
    set session_number (grep -oP "(?<=session: ).*" $target_md)
    set session_number (math $session_number + 1)
else
    set session_number 1
end

newline_prepper $target_md
echo "# Session $session_number" >>$target_md

xset s off
xset -dpms
$script_dir/scripts/pool-record_input.fish $uuid &
echo $target_md >/tmp/obsidian_last.txt

obsidian "obsidian://$target_md" >/dev/null 2>&1 &
if grep 'plaunch:' $target_md
    set tar_launch (grep -oP '(?<=plaunch: ).*' $target_md)
    eval "nohup $tar_launch &"
end

set start (date +%s)

echo "1 to end session and log it"
read user_value
while true
    if string match -qr 1 $user_value
        break
    else
        echo "Invalid input, only 1 is allowed, try again:"
        read user_value
    end
end

echo "Enter what this session was about"
read header_title

xset s on
xset +dpms
kill $(jobs -p)

set end (date +%s)
set cur_date (date +%d.%m.%y)
set result_time (math $end - $start)
set result_minutes (math round $result_time / 60)

if test $user_value -gt 0
    if grep -q 'session:' $target_md
        cp $target_md /tmp/clone.md
        awk '/session:/ { 
  for (i = 1; i <= NF; i++) { 
        if ($i ~ /^[0-9]+$/) $i = $i + 1; 
    } 
    } { print }' /tmp/clone.md >$target_md
    else
        sed -i "/^tags:/i\\session: 1" "$target_md"
    end

    if grep -q 'time:' $target_md
        cp $target_md /tmp/clone.md
        awk -v var="$result_time" '/time:/ { 
  for (i = 1; i <= NF; i++) { 
        if ($i ~ /^[0-9]+$/) $i = $i + var; 
    } 
    } { print }' /tmp/clone.md >$target_md
    else
        sed -i "/^session:/i\\time: $result_time" "$target_md"
    end
end

if test $user_value -eq 0
    sed -i "/# Session $session_number/d" "$target_md"
end

set date_last (date +%Y-%m-%d)
if grep -q 'date:' $target_md
    sed -i '/date:/d' "$target_md"
end
sed -i "/^tags:/i\\date: $date_last" "$target_md"
sed -i "/^# Session $session_number/a\\>[!info] $result_minutes minutes - $cur_date" "$target_md"
sed -i "s/Session $session_number/S$session_number - $header_title/g" $target_md

rm /tmp/the-pool.txt
rm /tmp/obsidian_last.txt
