#! /usr/bin/env fish

set script_dir (realpath (status dirname))
set obsidian_folder (ot_config_grab "ObsidianMainFolder")
set notes (ot_config_grab "NotesFolder")

set config_path $HOME/.config/ortscripts/the-idea.json
set protocol (jq '.[]' $config_path | jq '.protocol' | fzf)
set folder (jq -r ".[] | select(.protocol == $protocol) | .folder" $config_path)
set tags (jq -r ".[] | select(.protocol == $protocol) | .tags[]" $config_path)
set properties (jq -r ".[] | select(.protocol == $protocol) | .properties[]" $config_path)

set title (gum input --placeholder "Title")
set final_path "$obsidian_folder/$notes/$folder/$title.md"

echo --- >>$final_path
echo "tags:" >>$final_path
for i in $tags
    echo "  - $i" >>$final_path
end

for i in $properties
    echo "$i:" >>$final_path
    set check
    while not string match 0 $check
        set check (gum input --placeholder $i)
        if not string match 0 $check
            echo "  - $check" >>$final_path
        end
    end
end

set number_exists (jq ".[] | select(.protocol == $protocol)" $config_path | jq 'has("number")')
if $number_exists
    set number_property (jq -r ".[] | select(.protocol == $protocol) | .number" $config_path)
    echo "$number_property: $(gum input --placeholder $number_property)" >>$final_path
end
echo --- >>$final_path
echo "" >>$final_path
echo "# Core" >>$final_path
echo $(gum input --placeholder "Core Text") >>$final_path
echo "" >>$final_path

set check 1
while not string match 0 $check
    set check (gum input --placeholder "Brainstorming")
    if not string match 0 $check
        if grep -q "# Brainstorming" $final_path
        else
            echo "# Brainstorming" >>$final_path
        end
        echo "- $check" >>$final_path
    end
end
