#! /usr/bin/env fish

function get_priority
    switch $argv[1]
        case S
            echo 1
        case A
            echo 2
        case B
            echo 3
        case C
            echo 4
        case D
            echo 5
        case E
            echo 6
        case F
            echo 7
    end
end

function help_function
    echo "  -s       Respects Sequence"
    echo "  -i       Reverses selection, making the last used keys the first to appear, which turns the list into a pseudo history"
    echo "  -k       Activates keyring feature"
    echo "  -a       Activates agenda"
end

argparse --name=pool i/history s/sequence k/keyring a/agenda h/help 'n/name=' -- $argv
or return

set script_dir (realpath (status dirname))
set obsidian_folder (ot_config_grab "ObsidianMainFolder")
set obsidian_resource (ot_config_grab "ObsidianResourceFolder")
set notes (ot_config_grab "NotesFolder")
set default_pool_array (rg -l "^(I|Q|W|D):" $obsidian_folder/$notes)

if set -q _flag_h
    help_function
    exit
end

if set -q _flag_k
    rm /tmp/keyring_awk_result
    set key_array_filelist (rg -l "^K:" $obsidian_folder/$notes)
    set keyring_select (rg "^keyring:" $key_array_filelist | rg -o "#.*\b" | sort -u | string trim -lr | fzf --delimiter='#' --with-nth=-1)
    set keyring_file_list (rg -l "keyring: $keyring_select" $key_array_filelist)
    for i in $keyring_file_list
        awk -v term="$keyring_select" 'BEGIN { RS=""; FS="\n" } $0 ~ term { print $0 "\n" }' $i >>/tmp/keyring_awk_result
    end
    set key_array (rg --no-filename --no-line-number "^K:" /tmp/keyring_awk_result)
else
    set key_array (rg --no-filename --no-line-number "^K:" $obsidian_folder/$notes)
end

set sorted_key_array (
for line in $key_array
    # extract timestamp using regex
    set ts (string match -r '\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}' -- $line)
    if test -z "$ts"
        set ts "0000-00-00 00:00:00" # fallback if no timestamp
    end
    printf "%s\t%s\n" "$ts" "$line"
end | sort | cut -f2-)

if set -q _flag_i
    set sorted_key_array (printf "%s\n" $sorted_key_array | tac)
end

if set -q _flag_a
    set key_array_filelist (rg -l "^K:" $obsidian_folder/$notes)
    set agenda_keys (rg -oP "(?<=^agenda: ).*" $key_array_filelist | sort -u | string trim -lr)
    for i in $agenda_keys
        set key_file (echo $i | string split ":")[1]
        set key_of_agenda (echo $i | string split ":")[2]
        set agenda_temp (mktemp)
        awk -v term="$key_of_agenda" 'BEGIN { RS=""; FS="\n" } $0 ~ term { print $0 "\n" }' $key_file >$agenda_temp
        set priority (echo $key_of_agenda | rg -o "^.")
        set agenda_date (echo $key_of_agenda | rg -o "....-..-..")
        set key_header (cat $agenda_temp | rg "^K:" | string split "`")[1]
        set agenda_plus_key_header "[$priority] - [$agenda_date] | $key_header"
        set agenda_plus_key_header_array $agenda_plus_key_header_array $agenda_plus_key_header
    end

    set today (date +%s)
    set tmpfile (mktemp)

    for item in $agenda_plus_key_header_array
        set letter (string match -r '\[(.)\]' -- $item | string sub -s 2 -l 1 | string trim -lr)
        set date_str (string match -r '\[(\d{4}-\d{2}-\d{2})\]' -- $item | string trim -c '[]' | sort -u)
        set date_epoch (date -d $date_str +%s 2>/dev/null)
        set delta (math "abs($date_epoch - $today)")
        printf "%02d\t%09d\t%s\n" (get_priority $letter) $delta "$item" >>$tmpfile
    end

    set final_sorted_agenda (sort -n $tmpfile | cut -f3-)
    rm $tmpfile
end

for i in $sorted_key_array
    set trim_sorted_key_array $trim_sorted_key_array (echo $i | string split "`")[1]
end

if set -q _flag_a
    set select_key (for i in $final_sorted_agenda; echo $i; end | fzf --no-sort --preview "$script_dir/scripts/the-key-fzf.fish {}")

else
    set select_key (for i in $trim_sorted_key_array; echo $i; end | fzf --no-sort --delimiter='K: ' --with-nth=-1 --preview "$script_dir/scripts/the-key-fzf.fish {}")
end
set select_key_trim (echo $select_key | string trim -r)
set key_md (rg -l $select_key $obsidian_folder/$notes)
set tmp_key_contents /tmp/the-key-content

set key_date (date +"%Y-%m-%d %H:%M:%S")
sed -i "s/.*$select_key_trim.*/$select_key_trim `$key_date`/g" $key_md

awk -v search="$select_key_trim" '
      index($0, search) {flag=1}
      flag {print}
      /^$/ && flag {flag=0}
                              ' $key_md >$tmp_key_contents

set num 1
while true
    if rg "^string$num:" $tmp_key_contents
        set string (rg "^string$num:" $tmp_key_contents | rg -oP "(?<=string$num: ).*" | string trim -lr)
        set filtered_pool $filtered_pool (rg -lF "$string" $default_pool_array)
        set num (math $num + 1)
    else
        break
    end
end

if rg "^links:" $tmp_key_contents
    set md_links (rg "^links:" $tmp_key_contents | rg -o "\[.*\]" | string split "] [" | sed 's/\[//g' | sed 's/\]//g' | string trim -lr)
    set filtered_pool $filtered_pool (for i in $md_links; find $obsidian_folder/$notes/* -type f -name "$i.md"; end)
end

if rg "^tags:" $tmp_key_contents
    set tag_list (rg "^tags:" $tmp_key_contents | rg -o "#.*\b" | sed 's/#//g' | string split " " | string trim -lr)
    for i in $tag_list
        set filtered_pool $filtered_pool (rg -l "^  - $i\$" $default_pool_array)
    end
end

if rg "^c-tags:" $tmp_key_contents
    set ctag_list (rg "^c-tags:" $tmp_key_contents | rg -o "#.*\b" | sed 's/#//g' | string split " " | string trim -lr)
    set cpool_one (rg -l "^  - $ctag_list[1]\$" $default_pool_array)
    set cpool_two (rg -l "^  - $ctag_list[2]\$" $cpool_one)
    if test -z ctag_list[3]
        set cpool_three (rg -l "^  - $ctag_list[2]\$" $cpool_two)
        set filtered_pool $filtered_pool $cpool_three
    else
        set filtered_pool $filtered_pool $cpool_two
    end
end

if rg "^family:" $tmp_key_contents
    if rg "^family:.*parent" $tmp_key_contents
        set parent_name (rg -oP "(?<=parent: \"\[\[)[^\]]*" $key_md)
        set parent_file (find $obsidian_folder/$notes/* -type f -iname "$parent_name.md")
        set filtered_pool $filtered_pool $parent_file
    end

    if rg "^family:.*siblings" $tmp_key_contents
        set parent_name (rg -oP "(?<=parent: \"\[\[)[^\]]*" $key_md)
        set parent_file (find $obsidian_folder/$notes/* -type f -iname "$parent_name.md")
        set child_names (awk '/^child:/ {flag=1; next} flag && /^  - / {print $0} flag && !/^  - / {flag=0}' $parent_file | sed 's/[][]//g; s/"//g; s/-//g; s/^[[:space:]]*//; s/[[:space:]]*$//')
        for i in $child_names
            set child_file (find $obsidian_folder/$notes/* -type f -iname "$i.md")
            set filtered_pool $filtered_pool $child_file
        end
        set filtered_pool (for i in $filtered_pool; echo $i; end | sort -u)
    end

    if rg "^family:.*children" $tmp_key_contents
        set child_names (awk '/^child:/ {flag=1; next} flag && /^  - / {print $0} flag && !/^  - / {flag=0}' $key_md | sed 's/[][]//g; s/"//g; s/-//g; s/^[[:space:]]*//; s/[[:space:]]*$//')
        for i in $child_names
            set child_file (find $obsidian_folder/$notes/* -type f -iname "$i.md")
            set filtered_pool $filtered_pool $child_file
        end
        set filtered_pool (for i in $filtered_pool; echo $i; end | sort -u)
    end
end

if rg "^f-links:" $tmp_key_contents
    set md_links (rg "^f-links:" $tmp_key_contents | rg -o "\[.*\]" | string split "] [" | sed 's/\[//g' | sed 's/\]//g' | string trim -lr)
    set link_evil_pool (for i in $md_links; find $obsidian_folder/$notes/* -type f -name "$i.md"; end)
    for i in $filtered_pool
        if string match $i (for e in $link_evil_pool; echo $e; end)
        else
            set link_survivor_pool $link_survivor_pool $i
        end
    end
    set filtered_pool $link_survivor_pool
end

if rg "^f-tags:" $tmp_key_contents
    set ftag_list (rg "^f-tags:" $tmp_key_contents | rg -o "#.*\b" | sed 's/#//g' | string split " " | string trim -lr)

    set tag_evil_regex_ready (echo $ftag_list | sed 's/ /|/g')
    for i in $filtered_pool
        if rg -qP "^  - ($tag_evil_regex_ready)" "$i"
        else
            set tag_survivor_pool $tag_survivor_pool $i
        end
    end
    set filtered_pool $tag_survivor_pool
end

set fnum 1
while true
    if rg "^f-string$fnum:" $tmp_key_contents
        set string (rg "^f-string$fnum:" $tmp_key_contents | rg -oP "(?<=f-string$fnum: ).*" | string trim -lr)
        set filtered_pool (rg -lF --files-without-match "$string" $filtered_pool)
        set fnum (math $fnum + 1)
    else
        break
    end
end

if test -z $filtered_pool[1]
else
    set question_array (rg --no-filename --no-line-number "^(I|Q|W|D):" $filtered_pool)
end

if rg "^subtags:" $tmp_key_contents
    set subtag_list (rg "^subtags:" $tmp_key_contents | rg -o "#.*\b" | string split " " | string trim -lr)
    for i in $subtag_list
        set question_array $question_array (rg --no-filename --no-line-number "^(Q|I|D|W):.*$i" $default_pool_array)
    end
end

if rg "^a-subtags:" $tmp_key_contents
    set a_subtag_list (rg "^a-subtags:" $tmp_key_contents | rg -o "#.*\b" | string split " " | string trim -lr)
    set a_regex_ready (echo $a_subtag_list | sed 's/ /|/g')
    for i in $question_array
        if echo $i | rg -q "^(Q|I|D|W):.*$a_regex_ready"
            set a_array_sort $a_array_sort $i
        end
    end
    set question_array $a_array_sort
end

if rg "^f-subtags:" $tmp_key_contents
    set evil_subtag_list (rg "^f-subtags:" $tmp_key_contents | rg -o "#.*\b" | string split " " | string trim -lr)

    set subtag_evil_regex_ready (echo $evil_subtag_list | sed 's/ /|/g')
    for i in $question_array
        if echo $i | rg -q "$subtag_evil_regex_ready"
        else
            set survivor_subtag_pool $survivor_subtag_pool $i
        end
    end
    set question_array $survivor_subtag_pool
end

set sorted_question_array (for i in $question_array; echo $i; end | sort -u)
set question_array $sorted_question_array

set count_q (echo $question_array | rg -o "Q:" | wc -l)
set count_i (echo $question_array | rg -o "I:" | wc -l)
set count_w (echo $question_array | rg -o "W:" | wc -l)
set count_d (echo $question_array | rg -o "D:" | wc -l)
set count_c (echo $question_array | rg -o "(Q|I|W|D):" | wc -l)

set choice (gum choose --limit 1 "Combined ($count_c)" "Question ($count_q)" "Inspiration ($count_i)" "Wiki ($count_w)" "Drill ($count_d)"| string split " ")[1]
if string match -q Question $choice
    set selection Q
else if string match -q Inspiration $choice
    set selection I
else if string match -q Wiki $choice
    set selection W
else if string match -q Drill $choice
    set selection D
else if string match -q Combined $choice
    set selection "(Q|I|W|D)"
end

for i in $question_array
    if echo $i | rg -q "^$selection"
        set question_array_sort $question_array_sort $i
    end
end

set question_array $question_array_sort

# Sorting Algorithm
for i in $question_array
    if echo $i | rg -q "....-..-.. ..:..:.."
        set raw_date (echo "$i" | rg -o "....-..-.. ..:..:..")
        if echo $i | rg -P "(?<=S-Value: )[-0-9]*"
            set raw_value (echo $i | rg -oP "(?<=S-Value: )[-0-9]*")
        else
            set raw_value 0
        end
        set unix_timestamp (date -d "$raw_date" +%s)
        set value_seconds (ot_config_grab "ValueSeconds")
        set final_second_value (math $raw_value x $value_seconds)
        set unix_result (math $unix_timestamp + $final_second_value)
    else
        set unix_result 0
    end
    set unix_array $unix_array "$unix_result $i"
end

set sorted_unix_array (for i in $unix_array
    echo $i 
end | sort -n)

for i in $sorted_unix_array
    set final_sorted_array $final_sorted_array (echo "$i" | rg -o "(Q|I|W|D).*")
end

if set -q _flag_s
    set x (printf "%s\n" $final_sorted_array | awk '
        {
            match($0, /#[0-9]+/)
            if (RSTART > 0) {
                num = substr($0, RSTART + 1, RLENGTH - 1)
            } else {
                num = 999999  # fallback if no #number
            }
            print num "\t" $0
        }
    ' | sort -n | cut -f2-)
    set final_sorted_array $x
end

rm /tmp/the-card_final_sorted_array
for i in $final_sorted_array
    echo $i >>/tmp/the-card_final_sorted_array
end

clear
source $script_dir/scripts/the-card-output.fish
