#! /usr/bin/env fish

function get_priority
    switch $argv[1]
        case S
            echo 1
        case A
            echo 2
        case B
            echo 3
        case C
            echo 4
        case D
            echo 5
        case E
            echo 6
        case F
            echo 7
    end
end

function help_function
    echo "  --- Modes ---"

    echo "  -a       Agenda"
    echo "  -k       Keyring"
    echo "  -f       Favorites"
    echo "  -c       Cleared cards"
    echo "  -q       Query your key contents for quick testing"
    echo ""
    echo "  -p       Palaces"
    echo "  -l       Deactivates 'lose' Memory Palace mode"
    echo ""
    echo "  -t       Trophy view"
    echo "  -g       Generate trophy file"
    echo ""
    echo "  --- Options ---"
    echo "  -i       Reverses List, by default this creates a history view"
    echo "  -s       Respects Sequence"
    echo "  -e       Re-enumerate Sequence"
    echo ""
    echo "  -r       Random key gets auto selected"
    echo "  -z       Card order gets randomized"
    echo ""
    echo "  -v       Activate video functionality"
    echo "  -m       Activates key sound file"
end

function true_multiline_block_ripgrep
    set temp_rg (mktemp)
    set card_type $argv[1]
    set key_string $argv[2]
    set only_key_header $argv[3]
    rg -U -oP --no-filename "$card_type:.*(?:\n(?!\s*\n).*)*?$key_string.*\$" $obsidian_folder/$notes >$temp_rg

    cat $temp_rg | while read line
        if echo $line | rg -q "($card_type:|$key_string)"
        else
            sed -i 1d $temp_rg
            continue
        end
        set puzzle_pieces $puzzle_pieces $line
        if not test -z $puzzle_pieces[2]
            if string match -q true $only_key_header
                set completed_puzzle "$puzzle_pieces[1]"
            else
                set completed_puzzle "$puzzle_pieces[2] | $puzzle_pieces[1]"
            end
            set -e puzzle_pieces
            echo $completed_puzzle
        end
    end

    rm $temp_rg
end

function check_tag_exists
    set key $argv[1]
    set tag $argv[2]
    if rg -U -oP --no-filename "$key.*(?:\n(?!\s*\n).*)*?$tag.*\$" $obsidian_folder/$notes

        echo true
    else
        echo false
    end
end

function set_sorted_key
    rm /tmp/keyring_awk_result
    set keyring_select $argv[1]
    set type $argv[2]
    if string match -q keyring $type
        set keyring_file_list (rg -lP "$type:.*(^|\s)$keyring_select(\s|\$)" $key_array_filelist)
    else if string match -q mp $type
        set keyring_file_list (rg -l "$type: \[\[$keyring_select\]\]" $key_array_filelist)
    end
    for i in $keyring_file_list
        awk -v term="$keyring_select" 'BEGIN { RS=""; FS="\n" } $0 ~ term { print $0 "\n" }' $i >>/tmp/keyring_awk_result
    end
    set key_array (rg --no-filename --no-line-number "^K:" /tmp/keyring_awk_result)

    set sorted_key_array (
    for line in $key_array
    set ts (string match -r '\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}' -- $line)
    if test -z "$ts"
        set ts "0000-00-00 00:00:00" # fallback if no timestamp
    end
    printf "%s\t%s\n" "$ts" "$line"
    end | sort | cut -f2-)

    for i in $sorted_key_array
        set sortyboy $sortyboy (echo $i | string split "`")[1]
    end
    set trim_sorted_key_array $sortyboy
end

argparse --name=pool r/random z/zufall i/history s/sequence e/edit k/keyring a/agenda c/cleared f/favorite v/video q/query m/music p/palace t/trophy g/generate l/lose h/help 'n/name=' -- $argv
or return

set script_dir (realpath (status dirname))
set obsidian_folder (ot_config_grab "ObsidianMainFolder")
set obsidian_resource (ot_config_grab "ObsidianResourceFolder")
set notes (ot_config_grab "NotesFolder")
set default_pool_array (rg -l "^(I|Q|T):" $obsidian_folder/$notes)

if not set -q _flag_k; or not set -q _flag_p
    set key_array (rg --no-filename --no-line-number "^K:" $obsidian_folder/$notes)
end

if set -q _flag_g
    set trophy_file ~/.config/ortscripts/thekey_trophies.txt
    if test -e $trophy_file
        rm $trophy_file
    end
    for i in $key_array
        $script_dir/the-key headless "$i"
    end
    exit
end

if string match headless $argv[1]
    set headless_mode_activated true
    set select_key $argv[2]
end

if set -q _flag_h
    help_function
    exit
end

set generate_thumbnail true
if set -q _flag_v
    set generate_thumbnail false
end

if set -q _flag_k
    rm /tmp/keyring_awk_result
    set key_array_filelist (rg -l "^K:" $obsidian_folder/$notes)
    set keyring_select (rg "^keyring:" $key_array_filelist | rg -o "#.*\b" | sort -u | string trim -lr | fzf -0 --query "$argv[1]" --delimiter='#' --with-nth=-1 --preview "$script_dir/scripts/the-key-fzf.fish {} keyring")
    if test -z $keyring_select
        exit
    end
    set keyring_file_list (rg -lP "keyring:.*(^|\s)$keyring_select(\s|\$)" $key_array_filelist)
    for i in $keyring_file_list
        awk -v term="$keyring_select" 'BEGIN { RS=""; FS="\n" } $0 ~ term { print $0 "\n" }' $i >>/tmp/keyring_awk_result
    end
    set key_array (rg --no-filename --no-line-number "^K:" /tmp/keyring_awk_result)
end

if set -q _flag_p
    rm /tmp/keyring_awk_result
    set key_array_filelist (rg -l "^K:" $obsidian_folder/$notes)
    set keyring_select (rg "^mp:" $key_array_filelist | rg -oP '(?<=mp: \[\[)[^\]]*' | sort -u | string trim -lr | fzf --no-sort --style=full --preview "$script_dir/scripts/media-fzf.fish {} mp")
    if test -z $keyring_select
        exit
    end
    set keyring_file_list (rg -l "mp: \[\[$keyring_select\]\]" $key_array_filelist)
    for i in $keyring_file_list
        awk -v term="$keyring_select" 'BEGIN { RS=""; FS="\n" } $0 ~ term { print $0 "\n" }' $i >>/tmp/keyring_awk_result
    end
    set key_array (rg --no-filename --no-line-number "^K:" /tmp/keyring_awk_result)
end

if set -q _flag_t

    set trophies_sorted (cat ~/.config/ortscripts/thekey_trophies.txt | sort -t '|' -k1,1nr)

    for i in $trophies_sorted
        set cut_out (echo "$i" | string split "|")[3]
        set cut_out (echo $cut_out | string split "`")[1]
        set cut_out (echo $cut_out | string trim -lr)
        set trophies_key $trophies_key $cut_out
    end
    set select_key (for i in $trophies_key; echo $i; end | fzf -0 --no-sort --delimiter='K: ' --with-nth=-1 --style=full --query "$argv[1]" --preview "$script_dir/scripts/the-key-fzf.fish {} trophy")
    if test -z $select_key
        exit
    end
end

set sorted_key_array (
for line in $key_array
    set ts (string match -r '\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}' -- $line)
    if test -z "$ts"
        set ts "0000-00-00 00:00:00" # fallback if no timestamp
    end
    printf "%s\t%s\n" "$ts" "$line"
end | sort | cut -f2-)

if set -q _flag_c
    set c_temp (mktemp)
    true_multiline_block_ripgrep K "cards_cleared:" >$c_temp
    #perl $script_dir/perl/add_to_key.pl "cards_cleared:" $obsidian_folder/$notes >$c_temp
    set sorted_key_array (cat $c_temp | awk '{for(i=1;i<=NF;i++){if($i ~ /^cards_cleared:/){print $(i+1) " " $0}}}' | sort -nr | cut -d' ' -f2-)
    rm $c_temp
end

if set -q _flag_f
    set c_temp (mktemp)
    true_multiline_block_ripgrep K "key_favorite:" >$c_temp
    #perl $script_dir/perl/add_to_key.pl "key_favorite:" $obsidian_folder/$notes >$c_temp
    set sorted_key_array (cat $c_temp | awk '{for(i=1;i<=NF;i++){if($i ~ /^key_favorite:/){print $(i+1) " " $0}}}' | sort -nr | cut -d' ' -f2-)
    rm $c_temp
end

if set -q _flag_i
    set sorted_key_array (printf "%s\n" $sorted_key_array | tac)
end

if set -q _flag_a
    set key_array_filelist (rg -l "^K:" $obsidian_folder/$notes)
    set agenda_keys (true_multiline_block_ripgrep K "agenda:")

    set date_list (mktemp)
    for i in $agenda_keys
        set split_key (echo $i | string split "|")
        set priority (echo $split_key[1] | rg -o "(S|A|B|C|D|E|F)")
        if echo $i | rg -q "(S|A|B|C|D|E|F) ....-..-.."
            set agenda_date (echo $split_key[1] | rg -o "(S|A|B|C|D|E|F) ....-..-.." | rg -o "....-..-..")
            echo "$agenda_date" >>$date_list
        end
        set key_header (echo $split_key[2] | string trim -lr)

        if test -z $agenda_date
            set agenda_plus_key_header "[$priority] | $key_header"
        else
            set agenda_plus_key_header "[$priority] - [$agenda_date] | $key_header"
        end
        set agenda_plus_key_header_array $agenda_plus_key_header_array $agenda_plus_key_header
        set -e agenda_date
    end

    set today (date +%s)
    set closest_date ""
    set min_diff ""

    for line in (cat $date_list)
        set timestamp (begin; date -d $line +%s 2>/dev/null; end)

        if test -z "$timestamp"
            continue
        end

        set diff (math "abs($timestamp - $today)")

        if test -z "$min_diff" -o $diff -lt $min_diff
            set min_diff $diff
            set closest_date $line
        end
    end

    echo $closest_date
    rm $date_list

    set tmpfile (mktemp)

    for item in $agenda_plus_key_header_array
        set letter (string match -r '\[(.)\]' -- $item | string sub -s 2 -l 1 | string trim -lr)
        set date_str (string match -r '\[(\d{4}-\d{2}-\d{2})\]' -- $item | string trim -c '[]' | sort -u)
        set date_epoch (date -d $date_str +%s 2>/dev/null)
        set delta (math "abs($date_epoch - $today)")
        printf "%02d\t%09d\t%s\n" (get_priority $letter) $delta "$item" >>$tmpfile
    end

    set final_sorted_agenda (sort -n $tmpfile | cut -f3-)
    rm $tmpfile
end

for i in $sorted_key_array
    set trim_sorted_key_array $trim_sorted_key_array (echo $i | string split "`")[1]
end

if set -q _flag_r
    set array_length (count $trim_sorted_key_array)
    set random_selection (random 1 $array_length)
    set select_key $trim_sorted_key_array[$random_selection]
end

if string match true $headless_mode_activated; or set -q _flag_t; or set -q _flag_r
else
    if set -q _flag_a
        set select_key (for i in $final_sorted_agenda; echo $i; end | sed "s/\] - \[$closest_date/\] ⏰\[$closest_date/g" | fzf --no-sort --style=full --preview "$script_dir/scripts/the-key-fzf.fish {}")
        if test -z $select_key
            exit
        end
    else
        while test -z $select_key
            set select_key (for i in $trim_sorted_key_array; echo $i; end | fzf -0 --no-sort --delimiter='K: ' --with-nth=-1 --style=full --query "$argv[1]" --preview "$script_dir/scripts/the-key-fzf.fish {}")
            if test -z $select_key
                if set -q _flag_p
                    set keyring_select (rg "^mp:" $key_array_filelist | rg -oP '(?<=mp: \[\[)[^\]]*' | sort -u | string trim -lr | fzf --no-sort --style=full --preview "$script_dir/scripts/media-fzf.fish {} mp")
                    set_sorted_key $keyring_select mp
                end
                if set -q _flag_k
                    set keyring_select (rg "^keyring:" $key_array_filelist | rg -o "#.*\b" | sort -u | string trim -lr | fzf -0 --query "$argv[1]" --delimiter='#' --with-nth=-1 --preview "$script_dir/scripts/the-key-fzf.fish {} keyring")
                    set_sorted_key $keyring_select keyring
                end
            end
        end
    end
    if echo $select_key | rg "^\[.\]"; or echo $select_key | rg "^key"; or echo $select_key | rg "^cards_cleared"
        set select_key (echo $select_key | string split " | ")[2]
    end
end
set select_key_trim (echo $select_key | string trim -lr)
if string match -q "K:" $select_key_trim
    echo "Key is empty, exiting out of safety"
    exit
end

set key_md (rg -lF $select_key $obsidian_folder/$notes)
set tmp_key_contents /tmp/the-key-content

awk -v search="$select_key_trim" '
      index($0, search) {flag=1}
      flag {print}
      /^$/ && flag {flag=0}
                              ' $key_md >$tmp_key_contents

if set -q _flag_m
    set sound_file_name (rg -oP "(?<=sound:).*" $tmp_key_contents | string trim -lr)
    set sound_file (find $obsidian_folder/$obsidian_resource/* -name "$sound_file_name")
    while test -z $lsound_mpv
        mpv --no-video --loop "$sound_file" >/dev/null &
        set lsound_mpv $last_pid
        sleep 0.5
        if test -d /proc/$lsound_mpv
            echo "Music should work"
        else
            echo "Music didn't start, restarting"
            set -e lsound_mpv
        end
    end
end

set num 1
while true
    if rg "^string$num:" $tmp_key_contents
        set string (rg "^string$num:" $tmp_key_contents | rg -oP "(?<=string$num: ).*" | string trim -lr)
        set filtered_pool $filtered_pool (rg -lF "$string" $default_pool_array)
        set num (math $num + 1)
    else
        break
    end
end

set num 1
while true
    if rg "^regex$num:" $tmp_key_contents
        set regex (rg "^regex$num:" $tmp_key_contents | rg -oP "(?<=regex$num: ).*" | sed 's/"//g' | string trim -lr)
        set filtered_pool $filtered_pool (rg -lP $regex $default_pool_array)
        set num (math $num + 1)
    else
        break
    end
end

if rg "^links:" $tmp_key_contents
    set md_links (rg "^links:" $tmp_key_contents | rg -o "\[.*\]" | string split "] [" | sed 's/\[//g' | sed 's/\]//g' | string trim -lr)
    set filtered_pool $filtered_pool (for i in $md_links; find $obsidian_folder/$notes/* -type f -name "$i.md"; end)
end

set mindpalace_format false
if rg "^mp:" $tmp_key_contents
    set mindpalace_format true
end

if set -q _flag_l
    set mindpalace_format false
end

if rg "^tags:" $tmp_key_contents
    set tag_list (rg "^tags:" $tmp_key_contents | rg -o "#.*\b" | sed 's/#//g' | string split " " | string trim -lr)
    for i in $tag_list
        set filtered_pool $filtered_pool (rg -l "^  - $i\$" $default_pool_array)
    end
end

if rg "^family:" $tmp_key_contents
    if rg "^family:.*parent" $tmp_key_contents
        set parent_name (rg -oP "(?<=parent: \"\[\[)[^\]]*" $key_md)
        set parent_file (find $obsidian_folder/$notes/* -type f -iname "$parent_name.md")
        set filtered_pool $filtered_pool $parent_file
    end

    if rg "^family:.*siblings" $tmp_key_contents
        set parent_name (rg -oP "(?<=parent: \"\[\[)[^\]]*" $key_md)
        set parent_file (find $obsidian_folder/$notes/* -type f -iname "$parent_name.md")
        set child_names (awk '/^child:/ {flag=1; next} flag && /^  - / {print $0} flag && !/^  - / {flag=0}' $parent_file | sed 's/[][]//g; s/"//g; s/-//g; s/^[[:space:]]*//; s/[[:space:]]*$//')
        for i in $child_names
            set child_file (find $obsidian_folder/$notes/* -type f -iname "$i.md")
            set filtered_pool $filtered_pool $child_file
        end
        set filtered_pool (for i in $filtered_pool; echo $i; end | sort -u)
    end

    if rg "^family:.*children" $tmp_key_contents
        set child_names (awk '/^child:/ {flag=1; next} flag && /^  - / {print $0} flag && !/^  - / {flag=0}' $key_md | sed 's/[][]//g; s/"//g; s/-//g; s/^[[:space:]]*//; s/[[:space:]]*$//')
        for i in $child_names
            set child_file (find $obsidian_folder/$notes/* -type f -iname "$i.md")
            set filtered_pool $filtered_pool $child_file
        end
        set filtered_pool (for i in $filtered_pool; echo $i; end | sort -u)
    end
end

if rg "^f-links:" $tmp_key_contents
    set md_links (rg "^f-links:" $tmp_key_contents | rg -o "\[.*\]" | string split "] [" | sed 's/\[//g' | sed 's/\]//g' | string trim -lr)
    set link_evil_pool (for i in $md_links; find $obsidian_folder/$notes/* -type f -name "$i.md"; end)
    for i in $filtered_pool
        if string match $i (for e in $link_evil_pool; echo $e; end)
        else
            set link_survivor_pool $link_survivor_pool $i
        end
    end
    set filtered_pool $link_survivor_pool
end

if rg "^f-tags:" $tmp_key_contents
    set ftag_list (rg "^f-tags:" $tmp_key_contents | rg -o "#.*\b" | sed 's/#//g' | string split " " | string trim -lr)

    set tag_evil_regex_ready (echo $ftag_list | sed 's/ /|/g')
    for i in $filtered_pool
        if rg -qP "^  - ($tag_evil_regex_ready)\$" "$i"
        else
            set tag_survivor_pool $tag_survivor_pool $i
        end
    end
    set filtered_pool $tag_survivor_pool
end

set fnum 1
while true
    if rg "^f-string$fnum:" $tmp_key_contents
        set string (rg "^f-string$fnum:" $tmp_key_contents | rg -oP "(?<=f-string$fnum: ).*" | string trim -lr)
        set filtered_pool (rg -lF --files-without-match "$string" $filtered_pool)
        set fnum (math $fnum + 1)
    else
        break
    end
end

if test -z $filtered_pool[1]
else
    set question_array (rg --no-filename --no-line-number "^(I|Q|T):" $filtered_pool)
end

if rg "^subtags:" $tmp_key_contents
    set subtag_list (rg "^subtags:" $tmp_key_contents | rg -o "#.*\b" | string split " " | string trim -lr)
    for i in $subtag_list
        set question_array $question_array (true_multiline_block_ripgrep "(Q|I|T)" $i true)
    end
end

set cnum 1
while true
    if rg "^cardstring$cnum:" $tmp_key_contents
        set cardstring (rg -oP "(?<=cardstring$cnum: ).*" $tmp_key_contents | string trim -lr)
        set question_array $question_array (true_multiline_block_ripgrep "(Q|I|T)" "$cardstring" true $default_pool_array)
        set cnum (math $cnum + 1)
    else
        break
    end
end

if rg "^a-subtag:" $tmp_key_contents
    set a_subtag (rg "^a-subtag:" $tmp_key_contents | rg -o "#.*\b" | string split " " | string trim -lr)
    for i in $question_array
        if string match -q true (check_tag_exists $i $a_subtag)
            set a_array_sort $a_array_sort $i
        end
    end
    set question_array $a_array_sort
end

if rg "^contains:" $tmp_key_contents
    set contains (rg -oP "(?<=contains: ).*" $tmp_key_contents | string trim -lr)
    set temp_contains (mktemp)
    true_multiline_block_ripgrep "(Q|I|T)" "$contains" true >$temp_contains
    set question_array (cat $temp_contains)
    rm $temp_contains
end

if rg "^uuid:" $tmp_key_contents
    set contains ( rg "uuid" $tmp_key_contents | rg -o '\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b')
    set temp_contains (mktemp)
    true_multiline_block_ripgrep "(Q|I|T)" "$contains" true >$temp_contains
    set question_array (cat $temp_contains)
    rm $temp_contains
end

if rg "^mpid:" $tmp_key_contents
    set contains ( rg "mpid" $tmp_key_contents | rg -o '\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b')
    set temp_contains (mktemp)
    true_multiline_block_ripgrep "(Q|I|T)" "$contains" true >$temp_contains
    set question_array (cat $temp_contains)
    rm $temp_contains
end

if rg "^remove:" $tmp_key_contents
    set remove (rg -oP "(?<=remove: ).*" $tmp_key_contents | string trim -lr)
    set temp_remove (mktemp)

    for i in $question_array
        set true_file_md (rg -lF "$i" $default_pool_array)
        for r in $remove
            perl $script_dir/perl/exists.pl "$i" "$r" $true_file_md >>$temp_remove
        end
        if test -s $temp_remove
        else
            set removed_question_array $removed_question_array $i
        end
        rm $temp_remove
    end
    set question_array $removed_question_array
end

set sorted_question_array (for i in $question_array; echo $i; end | sort -u)
set question_array $sorted_question_array

for i in $question_array
    if echo $i | rg -q '\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b'
    else
        set removed_zero $removed_zero $i
    end
end
set question_array $removed_zero

if string match true $headless_mode_activated
else
    set count_q (echo $question_array | rg -o "Q:" | wc -l)
    set count_i (echo $question_array | rg -o "I:" | wc -l)
    set count_t (echo $question_array | rg -o "T:" | wc -l)
    set count_c (echo $question_array | rg -o "(Q|I|T):" | wc -l)

    if rg "^timer:" $tmp_key_contents
        set choice (rg -oP "(?<=timer: ).*" $tmp_key_contents | string trim -lr)
        set second_counter $choice
    end

    if rg "^skip:" $tmp_key_contents
        set choice (rg -oP "(?<=skip: ).*" $tmp_key_contents | string trim -lr)
    else
        set choice (gum choose --limit 1 "Combined ($count_c)" "Question ($count_q)" "Inspiration ($count_i)" "Task ($count_t)"| string split " ")[1]
    end
    if string match -q Question $choice
        set selection Q
    else if string match -q Inspiration $choice
        set selection I
    else if string match -q Task $choice
        set selection T
    else if string match -q Combined $choice
        set selection "(Q|I|T)"
    end

    for i in $question_array
        if echo $i | rg -q "^$selection:"
            set selection_filtered_array $selection_filtered_array $i
        end
    end
    set question_array $selection_filtered_array
end

# Sorting Algorithm
for i in $question_array
    if echo $i | rg -q "....-..-.. ..:..:.."
        set raw_date (echo "$i" | rg -o "....-..-.. ..:..:..")
        if echo $i | rg -Pq "(?<=S-Value: )[-0-9]*"
            set raw_value (echo $i | rg -oP "(?<=S-Value: )[-0-9]*")
        else
            set raw_value 0
        end
        set unix_timestamp (date -d "$raw_date" +%s)
        set value_seconds (ot_config_grab "ValueSeconds")
        set final_second_value (math $raw_value x $value_seconds)
        set unix_result (math $unix_timestamp + $final_second_value)
    else
        set unix_result 0
    end
    set unix_array $unix_array "$unix_result $i"
end

set sorted_unix_array (for i in $unix_array
    echo $i 
end | sort -n)

for i in $sorted_unix_array
    set final_sorted_array $final_sorted_array (echo "$i" | rg -o "(Q|I|T).*")
end

if set -q _flag_s
    set x (printf "%s\n" $final_sorted_array | awk '
        {
          if (match($0, /#[0-9]+(\.[0-9]+)?/)) {
              raw = substr($0, RSTART + 1, RLENGTH - 1)  # remove #
              split(raw, parts, ".")
              int_part = parts[1]
              dec_part = (length(parts) > 1) ? parts[2] : "0"
              dec_part = sprintf("%-04s", dec_part)  # pad decimals for proper sort
              sort_key = int_part "." dec_part
          } else {
              sort_key = "999999.9999"
          }
          print sort_key "\t" $0
        }
' | sort -n | cut -f2-)

    set final_sorted_array $x
end

if set -q _flag_z
    set shuffled (printf "%s\n" $final_sorted_array | shuf)
    set final_sorted_array $shuffled
end

if test -e /tmp/the-card_final_sorted_array
    rm /tmp/the-card_final_sorted_array
end
for i in $final_sorted_array
    echo $i >>/tmp/the-card_final_sorted_array
end

clear

if set -q _flag_e
    cat /tmp/the-card_final_sorted_array
    gum input --placeholder "Press enter if you are satisfied with the order of this list"
    set new_number 1
    echo "--- New Order ---"
    cat /tmp/the-card_final_sorted_array | while read line
        set sequence_md (rg -lF "$line" $obsidian_folder/$notes)
        if echo $line | rg -q "#[0-9]+"
            set get_number (echo $line | rg -o "#[0-9]+")
            set modified_key (echo $line | string split "$get_number")[1]
            set modified_key (echo $modified_key | string trim -lr)
        else if echo $line | rg -q "`....-..-.."
            set modified_key (echo $line | string split "`")[1]
            set modified_key (echo $modified_key | string trim -lr)
        else
            set modified_key (echo $line | string trim -lr)
        end
        if echo $line | rg -q "`....-..-.."
            set date (echo $line | rg -o "`.*`")
            set replacement "$modified_key #$new_number $date"
        else
            set replacement "$modified_key #$new_number"
        end
        set new_number (math $new_number + 1)
        sed -i "s/$line/$replacement/g" $sequence_md
        echo $replacement
    end
    exit
end

if set -q _flag_q
    set one_card (cat /tmp/the-card_final_sorted_array | fzf --no-sort --style=full --query "$argv[1]" --preview "$script_dir/scripts/the-key-fzf.fish {}")
    if test -z $one_card
        exit
    end
    echo $one_card >/tmp/the-card_final_sorted_array
end
set the_key_activated 1

if string match -q true $headless_mode_activated
    echo "Currently working on $select_key_trim"
    set trophy_file ~/.config/ortscripts/thekey_trophies.txt
    set total_value 0
    set bronze 0
    set silver 0
    set gold 0
    set platinum 0
    set diamond 0
    set obsidian 0
    cat /tmp/the-card_final_sorted_array | while read line
        set trim (string trim -r -- $line)
        set trimmed (string split '`' -- $trim)[1]
        set target_md (rg -lF "$trimmed" $obsidian_folder/$notes)
        set card_content /tmp/headless_card_contents
        awk -v search="$trimmed" '
          index($0, search) {flag=1}
          flag {print}
          /^$/ && flag {flag=0} ' $target_md >$card_content
        if cat $card_content | rg "#bronze"
            set bronze (math $bronze + 1)
            set total_value (math $total_value + 1)
        else if cat $card_content | rg "#silver"
            set silver (math $silver + 1)
            set total_value (math $total_value + 2)
        else if cat $card_content | rg "#gold"
            set gold (math $gold + 1)
            set total_value (math $total_value + 4)
        else if cat $card_content | rg "#platinum"
            set platinum (math $platinum + 1)
            set total_value (math $total_value + 8)
        else if cat $card_content | rg "#diamond"
            set diamond (math $diamond + 1)
            set total_value (math $total_value + 16)
        else if cat $card_content | rg "#obsidian"
            set obsidian (math $obsidian + 1)
            set total_value (math $total_value + 32)
        end
    end
    if test $total_value -lt 1
    else
        echo "$total_value | bronze=$bronze silver=$silver gold=$gold platinum=$platinum diamond=$diamond obsidian=$obsidian | $select_key_trim" >>$trophy_file
    end
else
    source $script_dir/scripts/the-card-output.fish
end
