#! /usr/bin/env fish

argparse --name=gameinit f/flameshot p/pool h/help 'n/name=' -- $argv
or return

set obsidian_main (ot_config_grab "ObsidianMainFolder")
set notes_folder (ot_config_grab "NotesFolder")
set resource_folder (ot_config_grab "ObsidianResourceFolder")
set final_folder "$obsidian_main/$resource_folder/thumbnail"

set pool_folder (ot_config_grab "ThePoolFolder")
set screenshot_folder $obsidian_main/$resource_folder/$pool_folder

set obsidian_md (fd -t f -F ".md" $obsidian_main/$notes_folder | sort -r | fzf --delimiter='/' --with-nth=-1 --style=full --preview "$script_dir/scripts/media-fzf.fish {}")
set sanitized_name (basename -s ".md" $obsidian_md | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')

if set -q _flag_p
    if grep -q 'uuid:' $obsidian_md
        set uuid (grep -oP '(?<=uuid: ).*' $obsidian_md)
    else
        set uuid (uuidgen)
        sed -i "/^tags:/i\\uuid: $uuid" "$obsidian_md"
    end

    mkdir -p $screenshot_folder/$uuid
    echo \a
    set timestamp (date +%F_%H%M%S)
    set fs_name "$uuid-$timestamp.jpg"
    set cover_image (find "$HOME/Pictures/flameshot/" -maxdepth 1 -type f | gum choose)
    mv $cover_image $screenshot_folder/$uuid/$fs_name

    if grep "cover-img:" $obsidian_md
        echo -e "![[$fs_name]]\n" >>"$obsidian_md"
    else
        sed -i "/^tags:/i\\cover-img: \"![[$fs_name]]\"" "$obsidian_md"
    end

    set date_last (date +%Y-%m-%d)
    if grep -q 'date:' $obsidian_md
        sed -i '/date:/d' "$obsidian_md"
    end
    sed -i "/^tags:/i\\date: $date_last" "$obsidian_md"
    exit
end

mkdir -p $final_folder
set timestamp (date +%F_%H%M%S)
set fs_name "$sanitized_name-$timestamp.jpg"

set default_folder "$HOME/Pictures/"
if set -q _flag_f
    set default_folder "$HOME/Pictures/flameshot/"
end
set cover_image (find $default_folder -maxdepth 1 -type f | gum choose)
mv $cover_image $final_folder/$fs_name

if grep "cover-img:" $obsidian_md
    echo -e "![[$fs_name]]\n" >>"$obsidian_md"
else if grep "tags:" $obsidian_md
    sed -i "/^tags:/i\\cover-img: \"[[$fs_name]]\"" "$obsidian_md"
else
    sed -i "0,/^---/a\\cover-img: \"[[$fs_name]]\"" "$obsidian_md"
end
