#! /usr/bin/env fish

argparse --name=gameinit p/pool h/help 'n/name=' -- $argv
or return

set obsidian_main (ot_config_grab "ObsidianMainFolder")
set notes_folder (ot_config_grab "NotesFolder")
set resource_folder (ot_config_grab "ObsidianResourceFolder")
set final_folder "$obsidian_main/$resource_folder/thumbnail"

set pool_folder (ot_config_grab "ThePoolFolder")
set screenshot_folder $obsidian_main/$resource_folder/$pool_folder

set last_active_file (find $obsidian_main/$notes_folder/ -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -d' ' -f2-)

set sanitized_name (basename $last_active_file | sed 's/[^a-zA-Z0-9 ]//g; s/.md//g; s/ /-/g' | tr '[:upper:]' '[:lower:]')

if set -q _flag_p
    if grep -q 'uuid:' $last_active_file
        set uuid (grep -oP '(?<=uuid: ).*' $last_active_file)
    else
        set uuid (uuidgen)
        sed -i "/^tags:/i\\uuid: $uuid" "$last_active_file"
    end

    mkdir -p $screenshot_folder/$uuid
    echo \a
    set timestamp (date +%F_%H%M%S)
    set fs_name "$uuid-$timestamp.jpg"
    scrot -s $screenshot_folder/$uuid/$fs_name

    if grep "cover-img:" $last_active_file
        echo -e "![[$fs_name]]\n" >>"$last_active_file"
    else
        sed -i "/^tags:/i\\cover-img: \"![[$fs_name]]\"" "$last_active_file"
    end

    set date_last (date +%Y-%m-%d)
    if grep -q 'date:' $last_active_file
        sed -i '/date:/d' "$last_active_file"
    end
    sed -i "/^tags:/i\\date: $date_last" "$last_active_file"
    exit
end

mkdir -p $final_folder
set timestamp (date +%F_%H%M%S)
set fs_name "$sanitized_name-$timestamp.jpg"
scrot -s $final_folder/$fs_name

if grep "cover-img:" $last_active_file
    echo -e "![[$fs_name]]\n" >>"$last_active_file"
else
    sed -i "/^tags:/i\\cover-img: \"![[$fs_name]]\"" "$last_active_file"
end
