# Must be put in .config/ortscripts/ 

Version: 0.2b 
ObsidianMainFolder: /home/anon/ortup/important/notes/ortvault

# The specifc names for the folders inside your vault 
ObsidianResourceFolder: resources
# The name of the folder where your notes reside 
NotesFolder: notes

# This will be in your resources folder 
GameFolder: game
AnimeFolder: anime_db
MindPalaceFolder: mindpalace



ThePoolFolder: the-pool
PoolDeviceName: NuPhy
PoolScreenshotButton: KEY_SYSRQ
PoolSelectScreenshotButton: KEY_DELETE
PoolRecordButton: KEY_INSERT
PoolAudioButton: KEY_F1
PoolEscapeButton: KEY_BACKSPACE


# Profile 1 flag -v 
# select your device with evtest
# hook counter can be customized per game with hook-values property 
Profile1DeviceName: 8bitdo-numpad-kanata|8BitDo Retro 18 Numpad Keyboard
Profile1ControllerCheck: 0
Profile1ScreenshotButton: KEY_KP1
Profile1SelectScreenshotButton: KEY_KP4
Profile1RecordButton: KEY_KP2
Profile1AudioButton: KEY_KP3
Profile1EscapeButton: KEY_KP0 
Profile1HookCounter: 15
Profile1IdleCounter: 180

# Profile 2 flag -x 
Profile2DeviceName: Xbox
Profile2ControllerCheck: 1
#HoldButton only works if ControllerCheck is 1 
Profile2HoldButton: BTN_SELECT
Profile2ScreenshotButton: BTN_SOUTH
Profile2RecordButton: BTN_WEST
Profile2AudioButton: BTN_EAST
Profile2EscapeButton: ABS_HAT0Y
Profile2HookCounter: 20
Profile2IdleCounter: 180
Profile2InputBlock: ABS_R?[XY].*value -?[0-9]{1,4}([^0-9]|$) 

# Manga Reader 
MangaDeviceName: 8BitDo Retro R8 Mouse Adapter 8BitDo Retro R8 Mouse Adapter Keyboard
MangaScreenshot: KEY_A

# Profile 3 flag -w  

# This value shaves off seconds of the total playtime recorded in a session to compensate for startup time of the game. 
# Can be customized per game with hook-values property
StartupCompensator: 30


# Option to insert a timeline inside the note that tracks on what day you played for how many minutes, this has nothing to do with playtime recording, it's just an extra 
TimelineOption: 1
# Option to add a limit on how many minutes the first recorded session must be to be inserted into note, to avoid cluttering the timeline with pointless sessions 
SessionLimit: 15

# the-card 
# how many seconds is one point worth. 48 hours = 172800, 36 hours = 129600, 24 hours = 86400, 12 hours = 43200, 6 hours = 21600:
ValueSeconds: 86400 

# manga-reader
BrowserManga: firefox
