#! /usr/bin/env fish 
set file_path "/home/anon/ortup/important/notes/ortvault/notes/anime_db/myanimelist_downloader.md"
set img_folder /home/anon/ortup/important/notes/ortvault/resources/anime_db/anime
set md_folder /home/anon/ortup/important/notes/ortvault/notes/anime_db/anime

function help_function
    echo "myanimelist -c"
end

for i in $argv
    set array $array $i
end

argparse --name=gn a/anime h/help 'n/name=' -- $argv
or return

if set -q _flag_h
    hel_function
    exit
end

for item in $array
    echo "Processing anime metadata:"
    curl $item >myanime.html
    set title (cat myanime.html | rg -oP -m 1 '(?<=<strong>)[^<]*')
    set type (cat myanime.html | rg -oP -m 1 '(?<=php\?type=)[^<]*' | rg -oP '(?<=">)[^"]*')
    set s_episodes (cat myanime.html | rg -oP '(?<=<span id="curEps">)[^<]*')

    set santized_title (echo $title | sed -E 's/[^a-zA-Z0-9]+/ /g; s/^ //; s/ $//')
    set hyphen_title (echo $santized_title | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
    set hyphen_title "$hyphen_title-a"
    set file_title (echo $title | sed 's/://g; s/[\|/]/ /g')
    set jap_title (cat myanime.html | grep -oP '(?<=Japanese:</span> ).*')

    set md "$md_folder/$file_title.md"
    echo "here is md: $md"
    set date (cat myanime.html | grep -oP '... .?[0-9]+, [0-9]{4}' | head -n 1)
    set date (date -d $date +"%Y-%m-%d")
    set creation_date (date +"%Y-%m-%dT%H:%M:%S")
    # set type (cat myanime.html | grep -oP -m 1 '(?<=\| )[^ ]*')

    wget -O $img_folder/$hyphen_title.jpg (cat myanime.html | grep -oP -m 1 '(?<=data-src=")[^"]*')

    echo --- >>$md
    echo "title: \"$title\"" >>$md
    echo "jap_title: \"$jap_title\"" >>$md
    echo "date: $date" >>$md
    echo "creation_date: $creation_date" >>$md
    echo "url: $item" >>$md
    echo "type: $type" >>$md
    echo "episodes: $s_episodes" >>$md
    echo "watched: $m_episodes" >>$md
    echo "score: $score" >>$md
    echo "status: \"Plan to Watch\"" >>$md
    echo "cover-img: \"[[$hyphen_title.jpg]]\"" >>$md
    echo "tags:" >>$md
    echo "  - anime" >>$md
    echo "  - db" >>$md
    echo --- >>$md

end

rm myanime.html
