#! /usr/bin/env fish 

set obsidian_main (ot_config_grab "ObsidianMainFolder")
set obsidian_res $obsidian_main/(ot_config_grab "ObsidianResourceFolder")
set obsidian_note $obsidian_main/(ot_config_grab "NotesFolder")
set img_folder $obsidian_res/anime_db/manga
set md_folder $obsidian_note/anime_db/manga

#set array (sed -n 's/.*\(http[s]\?:\/\/[^ ]*\).*/\1/p' $file_path)
for i in $argv
    set array $array $i
end

for item in $array
    echo "Processing manga metadata:"
    curl $item >myanime.html

    set title (cat myanime.html | grep -oP '(?<=title" content=")[^"]*')
    set type (cat myanime.html | rg -oP -m 1 '(?<=php\?type=)[^<]*' | rg -oP '(?<=">)[^"]*')
    set total_chapter (cat myanime.html | grep -oP '(?<=Chapters:</span> ).*')
    set total_volumes (cat myanime.html | grep -oP '(?<=Volumes:</span> ).*')

    set santized_title (echo $title | sed -E 's/[^a-zA-Z0-9]+/ /g; s/^ //; s/ $//')
    set hyphen_title (echo $santized_title | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
    set hyphen_title "$hyphen_title-ml"
    set file_title (echo $title | sed 's/://g; s/[\|/]/ /g')
    set jap_title (cat myanime.html | grep -oP '(?<=Japanese:</span> )[^<]*')

    set md "$md_folder/$file_title.md"
    set date (cat myanime.html | grep -oP '... .?[0-9]+, [0-9]{4}' | head -n 1)
    set date (date -d $date +"%Y-%m-%d")
    set creation_date (date +"%Y-%m-%dT%H:%M:%S")
    set type (cat myanime.html | grep -oP -m 1 '(?<=\| )[^ ]*')
    if test $type = Light
        set type "Light Novel"
    end

    wget -O $img_folder/$hyphen_title.jpg (cat myanime.html | grep -oP -m 1 '(?<=data-src=")[^"]*')

    echo --- >>$md
    echo "title: \"$title\"" >>$md
    echo "jap_title: \"$jap_title\"" >>$md
    echo "date: $date" >>$md
    echo "creation_date: $creation_date" >>$md
    echo "url: $item" >>$md
    echo "type: $type" >>$md
    echo "volumes: $total_volumes" >>$md
    echo "read-volumes: " >>$md
    if test $type = "Light Novel"

    else
        echo "chapters: $total_chapter" >>$md
        echo "read-chapters: $read_chapters" >>$md
    end

    echo "score: $score" >>$md
    echo "status: \"Plan to Read\"" >>$md
    echo "cover-img: \"[[$hyphen_title.jpg]]\"" >>$md
    if test $type = "Light Novel"
        echo "tags:" >>$md
        echo "  - ln" >>$md
        echo "  - db" >>$md
    else
        echo "tags:" >>$md
        echo "  - manga" >>$md
        echo "  - db" >>$md
    end
    echo --- >>$md

end

rm myanime.html
