#! /usr/bin/env fish 

set obsidian_main (ot_config_grab "ObsidianMainFolder")
set obsidian_res $obsidian_main/(ot_config_grab "ObsidianResourceFolder")
set obsidian_note $obsidian_main/(ot_config_grab "NotesFolder")
set img_folder $obsidian_res/anime_db/anime
set md_folder $obsidian_note/anime_db/anime

function help_function
end

function string_sanitizer
    string replace -a '&amp;' '&' -- "$argv[1]"
end

for i in $argv
    set array $array $i
end

argparse --name=gn a/anime h/help 'n/name=' -- $argv
or return

if set -q _flag_h
    hel_function
    exit
end

for item in $array
    set html /tmp/myanime.html
    curl $item >$html

    set type_selector
    set type (cat $html | rg -oP -m 1 '(?<=php\?type=)[^<]*' | rg -oP '(?<=">)[^"]*')
    if echo $type | rg "Light Novel"
        set type_selector ln
    else if echo $type | rg Manga
        set type_selector manga
    else
        set type_selector anime
    end

    if string match anime $type_selector
        echo "Processing anime metadata:"
        set title (cat $html | rg -oP -m 1 '(?<=<strong>)[^<]*')
        set s_episodes (cat $html | rg -oP '(?<=<span id="curEps">)[^<]*')

        set santized_title (echo $title | sed -E 's/[^a-zA-Z0-9]+/ /g; s/^ //; s/ $//')
        set hyphen_title (echo $santized_title | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
        set hyphen_title "$hyphen_title-a"
        set file_title (echo $title | sed 's/://g; s/[\|/]/ /g')
        set jap_title (cat $html | grep -oP '(?<=Japanese:</span> ).*')

        set premier (rg -oP -m 1 '(?<=<a href="https://myanimelist.net/anime/season/)[^<]*' $html)
        set premier (string split '>' $premier)[2]
        sed -i "/^url:/a\\premiered: \"\[\[$premier\]\]\"" $file

        set studio (rg -oP '(?<=class="information studio author"><a href="/anime/producer/)[^<]*' $html)
        set studio (string split '>' $studio)[2]

        set genres (rg --multiline --multiline-dotall '<span class="dark_text">Genres?:</span>.*?<span itemprop="genre" style="display: none">.*?</div>' $html)
        set genres (echo $genres | rg -oP '(?<=<span itemprop="genre" style="display: none">)[^<]*')

        set themes (rg --multiline --multiline-dotall '<span class="dark_text">Themes?:</span>.*?<span itemprop="genre" style="display: none">.*?</div>' $html)
        set themes (echo $themes | rg -oP '(?<=<span itemprop="genre" style="display: none">)[^<]*')

        set demographic (rg --multiline --multiline-dotall '<span class="dark_text">Demographics?:</span>.*?<span itemprop="genre" style="display: none">.*?</div>' $html)
        set demographic (echo $demographic | rg -oP '(?<=<span itemprop="genre" style="display: none">)[^<]*')

        set source (rg --multiline --multiline-dotall '<span class="dark_text">Sources?:</span>.*?<a href="https://myanimelist.net/anime/.*?</div>' $html)
        set source (echo $source | rg -o 'related_entries">.*</a>' | rg -o ' .* ' | string trim -lr)

        set md "$md_folder/$file_title.md"
        echo "here is md: $md"
        set date (cat $html | grep -oP '... .?[0-9]+, [0-9]{4}' | head -n 1)
        set date (date -d $date +"%Y-%m-%d")
        set creation_date (date +"%Y-%m-%dT%H:%M:%S")

        wget -O $img_folder/$hyphen_title.jpg (cat $html | grep -oP -m 1 '(?<=data-src=")[^"]*')

        echo --- >>$md
        echo "title: \"$title\"" >>$md
        echo "jap_title: \"$jap_title\"" >>$md
        echo "date: $date" >>$md
        echo "source:" >>$md
        for i in $source
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "demographic:" >>$md
        for i in $demographic
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "themes:" >>$md
        for i in $themes
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "genres:" >>$md
        for i in $genres
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "studio:" >>$md
        for i in $studio
            echo "  - \"[[$i]]\"" >>$md
        end
        if string match Movie $type; or string match OVA $type; or string match ONA $type
        else
            echo "premiered:" >>$md
            for i in $premier
                echo "  - \"[[$i]]\"" >>$md
            end
        end
        echo "url: $item" >>$md
        echo "type: $type" >>$md
        if string match Movie $type
        else
            echo "episodes: $s_episodes" >>$md
            echo "watched: $m_episodes" >>$md
        end
        echo "score: $score" >>$md
        echo "status: \"Plan to Watch\"" >>$md
        echo "cover-img: \"[[$hyphen_title.jpg]]\"" >>$md
        echo "tags:" >>$md
        echo "  - anime" >>$md
        echo "  - db" >>$md
        echo "creation_date: $creation_date" >>$md
        echo --- >>$md
    else if string match manga $type_selector
        echo "Processing manga metadata:"

        set title (cat $html | grep -oP '(?<=title" content=")[^"]*')
        set total_chapter (cat $html | grep -oP '(?<=Chapters:</span> ).*')
        set total_volumes (cat $html | grep -oP '(?<=Volumes:</span> ).*')

        set santized_title (echo $title | sed -E 's/[^a-zA-Z0-9]+/ /g; s/^ //; s/ $//')
        set hyphen_title (echo $santized_title | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
        set hyphen_title "$hyphen_title-ml"
        set file_title (echo $title | sed 's/://g; s/[\|/]/ /g')
        set jap_title (cat $html | grep -oP '(?<=Japanese:</span> )[^<]*')

        set genres (rg --multiline --multiline-dotall '<span class="dark_text">Genres?:</span>.*?</div>' $html)
        set genres (echo $genres | rg -oP '(?<=title=")[^"]*')

        set themes (rg --multiline --multiline-dotall '<span class="dark_text">Themes?:</span>.*?</div>' $html)
        set themes (echo $themes | rg -oP '(?<=title=")[^"]*')

        set demographic (rg --multiline --multiline-dotall '<span class="dark_text">Demographic?:</span>.*?</div>' $html)
        set demographic (echo $demographic | rg -oP '(?<=title=")[^"]*')

        set serialization (rg --multiline --multiline-dotall '<span class="dark_text">Serialization?:</span>.*?</div>' $html)
        set serialization (echo $serialization | rg -oP '(?<=title=")[^"]*')

        set authors (rg -oP '(?<=<a href="/people/)[^<]*' $html | sort -u)
        set trim_list
        for i in $authors
            set trim (string split '>' $i)[2]
            set trim (string replace ',' '' $trim)
            set trim_list $trim_list $trim
        end
        set authors $trim_list

        set md "$md_folder/$file_title.md"
        set date (cat $html | grep -oP '... .?[0-9]+, [0-9]{4}' | head -n 1)
        set date (date -d $date +"%Y-%m-%d")
        set creation_date (date +"%Y-%m-%dT%H:%M:%S")

        wget -O $img_folder/$hyphen_title.jpg (cat $html | grep -oP -m 1 '(?<=data-src=")[^"]*')

        echo --- >>$md
        echo "title: \"$title\"" >>$md
        echo "jap_title: \"$jap_title\"" >>$md
        echo "authors:" >>$md
        for i in $authors
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "date: $date" >>$md
        echo "demographic:" >>$md
        for i in $demographic
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "serialization:" >>$md
        for i in $serialization
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "themes:" >>$md
        for i in $themes
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "genres:" >>$md
        for i in $genres
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "url: $item" >>$md
        echo "type: $type" >>$md
        echo "volumes: $total_volumes" >>$md
        echo "read-volumes: " >>$md
        echo "chapters: $total_chapter" >>$md
        echo "read-chapters: $read_chapters" >>$md
        echo "score: $score" >>$md
        echo "status: \"Plan to Read\"" >>$md
        echo "cover-img: \"[[$hyphen_title.jpg]]\"" >>$md
        echo "tags:" >>$md
        echo "  - manga" >>$md
        echo "  - db" >>$md
        echo "creation_date: $creation_date" >>$md
        echo --- >>$md
    else if string match ln $type_selector
        echo "Processing ln metadata:"

        set title (cat $html | grep -oP '(?<=title" content=")[^"]*')
        set total_volumes (cat $html | grep -oP '(?<=Volumes:</span> ).*')

        set santized_title (echo $title | sed -E 's/[^a-zA-Z0-9]+/ /g; s/^ //; s/ $//')
        set hyphen_title (echo $santized_title | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
        set hyphen_title "$hyphen_title-ml"
        set file_title (echo $title | sed 's/://g; s/[\|/]/ /g')
        set jap_title (cat $html | grep -oP '(?<=Japanese:</span> )[^<]*')

        set genres (rg --multiline --multiline-dotall '<span class="dark_text">Genres?:</span>.*?</div>' $html)
        set genres (echo $genres | rg -oP '(?<=title=")[^"]*')

        set themes (rg --multiline --multiline-dotall '<span class="dark_text">Themes?:</span>.*?</div>' $html)
        set themes (echo $themes | rg -oP '(?<=title=")[^"]*')
        set authors (rg -oP '(?<=<a href="/people/)[^<]*' $html | sort -u)
        set trim_list
        for i in $authors
            set trim (string split '>' $i)[2]
            set trim (string replace ',' '' $trim)
            set trim_list $trim_list $trim
        end
        set authors $trim_list

        set md "$md_folder/$file_title.md"
        set date (cat $html | grep -oP '... .?[0-9]+, [0-9]{4}' | head -n 1)
        set date (date -d $date +"%Y-%m-%d")
        set creation_date (date +"%Y-%m-%dT%H:%M:%S")

        wget -O $img_folder/$hyphen_title.jpg (cat $html | grep -oP -m 1 '(?<=data-src=")[^"]*')

        echo --- >>$md
        echo "title: \"$title\"" >>$md
        echo "jap_title: \"$jap_title\"" >>$md
        echo "authors:" >>$md
        for i in $authors
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "date: $date" >>$md
        echo "themes:" >>$md
        for i in $themes
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "genres:" >>$md
        for i in $genres
            echo "  - \"[[$i]]\"" >>$md
        end
        echo "url: $item" >>$md
        echo "type: $type" >>$md
        echo "volumes: $total_volumes" >>$md
        echo "read-volumes: " >>$md
        echo "score: $score" >>$md
        echo "status: \"Plan to Read\"" >>$md
        echo "cover-img: \"[[$hyphen_title.jpg]]\"" >>$md
        echo "tags:" >>$md
        echo "  - ln" >>$md
        echo "  - db" >>$md
        echo "creation_date: $creation_date" >>$md
        echo --- >>$md
    else
        echo "No type found, exiting"
        exit
    end
end

rm $html
