#! /usr/bin/env fish 
echo "hello world"
set html "/tmp/vgmdb.html"
set file_path /home/anon/ortup/important/notes/ortvault/notes/music_db/vgmdb_downloader.md
set img_folder /home/anon/ortup/important/notes/ortvault/resources/music_db/vgmdb
set md_folder /home/anon/ortup/important/notes/ortvault/notes/music_db/vgmdb
set sed_string "s/ & /-and-/g; s/+/-plus/g; s/ /-/g; s/'/-/g; s/[!:.]//g"
set script_dir (realpath (status dirname))
set extra_tag (cat $file_path | grep -oP '(?<=switch: ).*')

set link_array (sed -n 's/.*\(http[s]\?:\/\/[^ ]*\).*/\1/p' $file_path)
for item in $link_array
    node $script_dir/fetch-page.js "$item" >$html
    set interpret (xmllint --html --xpath '//tr[@class="maincred"][1]' $html 2>/dev/null | grep -oP '<a href="/artist/[0-9]*">[^<]*' | grep -oP '(?<=>).*')
    set title (cat $html | grep -oP '(?<=<span class="albumtitle" lang="en" style="display:inline">)[^<]*') | head -n 1
    set subtitle (string trim "$title[2]")
    set md_title (echo $title[1] | sed 's/://g; s/[\|/]/ /g')
    set hyphen_title (echo "$md_title-vgmdb" | tr '[:upper:]' '[:lower:]' | sed $sed_string)
    set img_link (cat $html | grep -oP '(?<=<div id="coverart" style="background-image: url\(\')[^\']*')
    set raw_date (cat $html | grep -oP '(?<=<a title="View albums released on )[^"]*')
    set month (date -d "$raw_date" +%m)
    set day (date -d "$raw_date" +%d)
    set year (date -d "$raw_date" +%Y)

    set md "$md_folder/$md_title.md"
    wget -O "$img_folder/$hyphen_title.jpg" $img_link

    echo --- >>$md
    echo "title: \"$title[1]\"" >>$md
    echo "interpret: \"$interpret\"" >>$md
    echo "url: \"$item\"" >>$md
    echo "date: \"$year-$month-$day\"" >>$md
    echo "cover-img: \"[[$hyphen_title.jpg]]\"" >>$md
    echo "tags:" >>$md
    echo "  - music" >>$md
    echo "  - db" >>$md
    echo "  - $extra_tag" >>$md
    echo --- >>$md
end
